blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('page/<int:page_id>/', views.index, name='index'),
    path('article/<str:article_slug>/', views.article, name='article'),
    path('category/', views.category, name='category'),
    path('category/page/<int:page_id>/', views.category, name='category'),
    path('category/<str:category_slug>/', views.category_detail, name='category_detail'),
    path('category/<str:category_slug>/page/<int:page_id>/', views.category_detail, name='category_detail'),
    path('tag/', views.tag, name='tag'),
    path('tag/page/<int:page_id>/', views.tag, name='tag'),
    path('tag/<str:tag_slug>/', views.tag_detail, name='tag_detail'),
    path('tag/<str:tag_slug>/page/<int:page_id>/', views.tag_detail, name='tag_detail'),
    path('archive/', views.archive, name='archive'),
    path('archive/<int:year>/<int:month>/', views.archive_detail, name='archive_detail'),
    path('archive/<int:year>/<int:month>/page/<int:page_id>/', views.archive_detail, name='archive_detail'),
    path('link/', views.link, name='link'),
    path('link/page/<int:page_id>/', views.link, name='link'),
    path('search/', views.search, name="search"),
    path('search/page/<int:page_id>/', views.search, name="search"),
    path('<str:article_slug>.html', views.article, name='page'),
]

control/urls.py
from django.urls import path

from . import views


app_name = 'control'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('forbidden/', views.forbidden, name='forbidden'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('personal-information/', views.personal_information, name='personal_information'),
    path('change-password/', views.change_password, name='change_password'),
    path('setting/', views.setting, name='setting'),
    path('manage/article/', views.article_list, name='article_list'),
    path('manage/article/page/<int:page_id>/', views.article_list, name='article_list'),
    path('manage/single-page/', views.page_list, name='page_list'),
    path('manage/single-page/page/<int:page_id>/', views.page_list, name='page_list'),
    path('manage/category/', views.category_list, name='category_list'),
    path('manage/category/page/<int:page_id>/', views.category_list, name='category_list'),
    path('manage/tag/', views.tag_list, name='tag_list'),
    path('manage/tag/page/<int:page_id>/', views.tag_list, name='tag_list'),
    path('manage/user/', views.user_list, name='user_list'),
    path('manage/user/page/<int:page_id>/', views.user_list, name='user_list'),
    path('manage/comment/', views.comment_list, name='comment_list'),
    path('manage/comment/page/<int:page_id>/', views.comment_list, name='comment_list'),
    path('manage/link/', views.link_list, name='link_list'),
    path('manage/link/page/<int:page_id>/', views.link_list, name='link_list'),
    path('create/article/', views.article_create, name='article_create'),
    path('create/page/', views.page_create, name='page_create'),
    path('create/category/', views.category_create, name='category_create'),
    path('create/tag/', views.tag_create, name='tag_create'),
    path('create/user/', views.user_create, name='user_create'),
    path('create/link/', views.link_create, name='link_create'),
    path('edit/article/<int:article_id>/', views.article_edit, name='article_edit'),
    path('edit/page/<int:page_id>/', views.page_edit, name='page_edit'),
    path('edit/category/<int:category_id>/', views.category_edit, name='category_edit'),
    path('edit/tag/<int:tag_id>/', views.tag_edit, name='tag_edit'),
    path('edit/user/<int:user_id>/', views.user_edit, name='user_edit'),
    path('edit/link/<int:link_id>/', views.link_edit, name='link_edit'),
]

nitroblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('control/', include('control.urls')),
    path('admin/', admin.site.urls),
]

control/models.py
from django.db import models

# Create your models here.

control/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import RequestContext
from django.urls import reverse
from django.db.models import F
from django.db import connection, ProgrammingError, IntegrityError
import hashlib, base64, datetime


from blog.common import *
from blog.models import *
from blog.views import get_basic_info, get_content_category_list
from .forms import *


def login(request):
    if request.session.get('is_login', None):
        return HttpResponseRedirect(reverse('control:dashboard', args=()))

    login_message = None

    if request.method == 'POST':
        form_info = LoginForm(request.POST)
        if form_info.is_valid():
            username = form_info.cleaned_data['username']
            password = form_info.cleaned_data['password']
            try:
                user = User.objects.get(username=username)
                if password_encrypt(password) == user.password:
                    request.session['is_login'] = True
                    request.session['user_id'] = user.id
                    user.last_login_time = datetime.datetime.now()
                    user.save()
                    return HttpResponseRedirect(reverse('control:dashboard', args=()))
                else:
                    login_message = '用户名或密码错误！'
            except User.DoesNotExist:
                login_message = '用户名或密码错误！'
        else:
            login_message = '请检查输入格式！'

    form_info = LoginForm()
    return render(request, 'control/login.html', locals())


def logout(request):
    if not request.session.get('is_login', None):
        return HttpResponseRedirect(reverse('control:login', args=()))

    request.session.flush()

    return HttpResponseRedirect(reverse('control:login', args=()))


def forbidden(request):
    if request.session.get('is_login') is None:
        return HttpResponseRedirect(reverse('control:login', args=()))

    return render(request, 'control/forbidden.html', locals())


def dashboard(request):
    if request.session.get('is_login') is None:
        return HttpResponseRedirect(reverse('control:login', args=()))

    number = {
        'article': Content.objects.filter(type='article').count(),
        'comment': Comment.objects.all().count(),
        'category': Meta.objects.filter(type='category').count(),
        'tag': Meta.objects.filter(type='tag').count(),
    }

    recent_article_list_query = '''
    SELECT title, slug, id
    FROM blog_content
    WHERE type = 'article'
    ORDER BY create_time DESC
    LIMIT 0, 10;
    '''

    recent_comment_list_query = '''
    SELECT blog_comment.text, blog_user.username
    FROM blog_comment, blog_user
    WHERE blog_comment.author_id_id = blog_user.id
    ORDER BY blog_comment.create_time DESC
    LIMIT 0, 10;
    '''

    cursor = connection.cursor()
    cursor.execute(recent_article_list_query)
    recent_article_list = cursor.fetchall()
    cursor.execute(recent_comment_list_query)
    recent_comment_list = cursor.fetchall()

    context = {
        'number': number,
        'recent_article_list': recent_article_list,
        'recent_comment_list': recent_comment_list,
    }

    return render(request, 'control/general/dashboard.html', context)


def personal_information(request):
    if request.session.get('is_login') is None:
        return HttpResponseRedirect(reverse('control:login', args=()))

    response_message = ''

    if request.method == 'POST':
        form_info = PersonalInformationForm(request.POST)
        if form_info.is_valid():
            operation_query = '''
            UPDATE blog_user
            SET mail = '%s',
            url = '%s',
            nickname = '%s'
            WHERE username = '%s';
            ''' % (form_info.cleaned_data['email'], form_info.cleaned_data['url'], form_info.cleaned_data['nickname'], User.objects.get(id=request.session['user_id']).username)
            try:
                cursor = connection.cursor()
                cursor.execute(operation_query)
                response_message = '更新成功！'
            except ProgrammingError:
                response_message = '更新失败！'
        else:
            response_message = '请检查输入格式！'

    user_info = User.objects.get(username=User.objects.get(id=request.session['user_id']).username)
    form_info = PersonalInformationForm()
    form_info['email'].initial = user_info.mail
    form_info['url'].initial = user_info.url
    form_info['nickname'].initial = user_info.nickname
    return render(request, 'control/general/personal_information.html', locals())


def change_password(request):
    if request.session.get('is_login') is None:
        return HttpResponseRedirect(reverse('control:login', args=()))

    response_message = ''

    if request.method == 'POST':
        form_info = PasswordChangeForm(request.POST)
        if form_info.is_valid():
            user = User.objects.get(username=User.objects.get(id=request.session['user_id']).username)
            if user.password == password_encrypt(form_info.cleaned_data['current_password']) and form_info.cleaned_data['new_password'] == form_info.cleaned_data['new_password_confirm']:
                try:
                    user.password = password_encrypt(form_info.cleaned_data['new_password'])
                    user.save()
                    response_message = '修改成功！'
                except (ProgrammingError, NameError):
                    response_message = '修改失败！'
            else:
                response_message = '密码输入错误！'
        else:
            response_message = '请检查输入格式！'

    form_info = PasswordChangeForm()
    return render(request, 'control/general/change_password.html', locals())


def article_list(request, page_id=1):
    if request.session.get('is_login') is None:
        return HttpResponseRedirect(reverse('control:login', args=()))

    if User.objects.get(id=request.session['user_id']).group != 'administrator' and User.objects.get(id=request.session['user_id']).group != 'writer':
        return HttpResponseRedirect(reverse('control:forbidden', args=()))

    response_message = ''

    if request.method == 'POST':
        article_id_list = request.POST.getlist('article_cid[]')
        article_id_set = ''
        if article_id_list:
            flag = 0
            for article_id in article_id_list:
                if flag > 0:
                    article_id_set += ', '
                article_id_set += article_id
                flag += 1
            operation_query = '''
            SELECT * FROM blog_content
            WHERE id in (%s) 
            ''' % article_id_set
            if User.objects.get(id=request.session['user_id']).group != 'administrator':
                operation_query += '''
                AND author_id_id = %s
                ''' % request.session['user_id']

            try:
                article_list = Content.objects.raw(operation_query)
                for article in article_list:
                    article.delete()
            except (NameError, ProgrammingError):
                response_message = '删除失败！'

    keyword = request.GET.get('keyword')
    category_id = request.GET.get('category')

    if keyword is None:
        keyword = ''
    if category_id is None:
        category_id = 0
    else:
        category_id = int(category_id)

    page_size = 10
    basic_info = get_basic_info(request)
    basic_info['number_of_article'] = 0

    number_of_article_query = '''
    SELECT COUNT(id)
    FROM blog_content
    WHERE type = 'article'
    '''

    if User.objects.get(id=request.session['user_id']).group == 'writer':
        number_of_article_query += '''
        AND author_id_id = %s
        ''' % request.session['user_id']

    if keyword != '':
        number_of_article_query += '''
        AND title LIKE '%%%%%s%%%%'
        ''' % keyword

    if category_id != 0:
        number_of_article_query += '''
        AND id in (
            SELECT content_id_id
            FROM blog_relationship
            WHERE meta_id_id = %s
        )
        ''' % category_id

    cursor = connection.cursor()
    cursor.execute(number_of_article_query)
    basic_info['number_of_article'] = cursor.fetchone()[0]
    basic_info['number_of_article_page'] = ceil(basic_info['number_of_article'], page_size)

    left_range = 0 + page_size * (page_id - 1)

    article_list_query = '''
    SELECT blog_content.id, blog_content.title, blog_content.edit_time, 
    COUNT(blog_comment.content_id_id), blog_content.slug, blog_content.author_id_id
    FROM blog_content LEFT OUTER JOIN blog_comment
    ON (blog_content.id = blog_comment.content_id_id)
    WHERE blog_content.type = 'article' 
    '''

    if User.objects.get(id=request.session['user_id']).group != 'administrator':
        article_list_query += '''
        AND blog_content.author_id_id = %s
        ''' % request.session['user_id']

    if keyword != '':
        article_list_query += '''
        AND blog_content.title LIKE '%%%%%s%%%%'
        ''' % keyword

    if category_id != 0:
        article_list_query += '''
        AND blog_content.id in (
            SELECT content_id_id
            FROM blog_relationship
            WHERE meta_id_id = %s
        )
        ''' % category_id

    article_list_query += '''
    GROUP BY blog_content.id
    ORDER BY blog_content.edit_time DESC
    LIMIT %s, %s;
    ''' % (left_range, page_size)

    cursor = connection.cursor()
    cursor.execute(article_list_query)
    article_list = cursor.fetchall()
    category_list_of_content = []

    for article_item in article_list:
        raw_category_list = get_content_category_list(article_item[0])
        category_list_of_content.append(raw_category_list)

    form_info = ArticleFilterForm({'keyword': keyword, 'category': category_id,})

    return render(request, 'control/manage/article_list.html', locals())


def page_list(request, page_id=1):

control/templates/control/base.html
{% load static %}
{% load control_extras %}
{% get_user_group_by_id request.session.user_id as user_group %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'control/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'control/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'control/fontawesome/css/all.css' %}">
        <title>Control Panel - Nitroblog</title>
    </head>
    <body>

        <div class="page-navbar">

            <nav class="navbar navbar-expand-lg navbar-dark shadow-sm bg-dark d-flex">

                <a class="navbar-brand page-navbar-title" href="#">Nitroblog 控制面板</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <span class="badge badge-primary page-navbar-username"><i class="fas fa-user"></i> {% get_user_username_by_id request.session.user_id %}</span>
                            <a href="{% url 'blog:index' %}" class="btn btn-warning page-navbar-logout" target="_blank"><i class="fas fa-home"></i> 打开主页</a>
                            <a href="{% url 'control:logout' %}" class="btn btn-danger page-navbar-logout"><i class="fas fa-sign-out-alt"></i> 退出登录</a>
                        </li>
                    </ul>
                </div>

            </nav>

        </div>

        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-2">

                    <div class="cp-sidebar">
                        <div class="card text-dark bg-dark mb-3">
                            <div class="card-header text-white">
                                <i class="fas fa-border-all"></i>通用
                            </div>
                            <ul class="list-group list-group-flush">
                                <a href="{% url 'control:dashboard' %}" class="list-group-item list-group-item-action"><i class="fas fa-tachometer-alt"></i>概要信息</a>
                                <a href="{% url 'control:personal_information' %}" class="list-group-item list-group-item-action"><i class="fas fa-user-edit"></i>个人信息</a>
                                <a href="{% url 'control:change_password' %}" class="list-group-item list-group-item-action"><i class="fas fa-key"></i>修改密码</a>
                                {% if user_group == 'administrator' %}
                                <a href="{% url 'control:setting' %}" class="list-group-item list-group-item-action"><i class="fas fa-cog"></i>系统设置</a>
                                {% endif %}
                            </ul>
                        </div>

                        {% if user_group == 'administrator' or user_group == 'writer' %}
                        <div class="card text-dark bg-dark mb-3">
                            <div class="card-header text-white">
                                <i class="fas fa-pen-nib"></i>撰写
                            </div>
                            <ul class="list-group ast-group-flush">
                                <a href="{% url 'control:article_create' %}" class="list-group-item list-group-item-action"><i class="far fa-file-alt"></i>撰写文章</a>
                                <a href="{% url 'control:page_create' %}" class="list-group-item list-group-item-action"><i class="fas fa-file"></i>创建独立页面</a>
                            </ul>
                        </div>

                        <div class="card text-dark bg-dark mb-3">
                            <div class="card-header text-white">
                                <i class="fas fa-sliders-h"></i>管理
                            </div>
                            <ul class="list-group list-group-flush">
                                <a href="{% url 'control:article_list' %}" class="list-group-item list-group-item-action"><i class="far fa-file-alt"></i>文章</a>
                                <a href="{% url 'control:page_list' %}" class="list-group-item list-group-item-action"><i class="fas fa-file"></i>独立页面</a>
                                <a href="{% url 'control:comment_list' %}" class="list-group-item list-group-item-action"><i class="far fa-comments"></i>评论</a>
                                <a href="{% url 'control:category_list' %}" class="list-group-item list-group-item-action"><i class="fas fa-cube"></i>分类</a>
                                <a href="{% url 'control:tag_list' %}" class="list-group-item list-group-item-action"><i class="fas fa-tags"></i>标签</a>
                                {% if user_group == 'administrator' %}
                                <a href="{% url 'control:link_list' %}" class="list-group-item list-group-item-action"><i class="fas fa-link"></i>链接</a>
                                <a href="{% url 'control:user_list' %}" class="list-group-item list-group-item-action"><i class="fas fa-user-friends"></i>用户</a>
                                {% endif %}
                            </ul>
                        </div>
                        {% endif %}
                    </div>

                </div>

                <div class="col-lg-10">

                    {% block container %}
                    {% endblock %}

                </div>
            </div>
        </div>

        <footer class="footer py-3">
            <span class="text-muted">Copyright &copy; 2019 Nitrogens.</span>
        </footer>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="{% static 'control/js/bootstrap.min.js' %}"></script>
        <script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});</script>
        <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>
        <script type="text/javascript" src="{% static 'control/js/math.js' %}"></script>
        <script type="text/javascript" src="{% static 'control/js/control.js' %}"></script>
  </body>
</html>

control/templates/control/forbidden.html
{% extends 'control/base.html' %}
{% block container %}
                    <div class="alert alert-warning" role="alert">
                        <i class="fas fa-exclamation-triangle"></i> 权限不够，拒绝访问。
                    </div>
{% endblock %}

control/templates/control/login.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'control/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'control/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'control/fontawesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'control/css/login.css' %}">
        <title>登录 - Nitroblog</title>
    </head>
    <body>
        <form class="form-signin" method="POST" action="{% url 'control:login' %}">
            {% csrf_token %}
            {% if login_message %}
            <div class="alert alert-warning" role="alert">
                <i class="fas fa-exclamation-triangle"></i> {{ login_message }}！
            </div>
            {% endif %}
            <h1 class="h3 mb-3 font-weight-normal text-center">登录到 Nitroblog</h1>
            {{ form_info.username }}
            {{ form_info.password }}
            <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
            <p class="mt-5 mb-3 text-muted">&copy; 2019 Nitroblog</p>
        </form>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="{% static 'control/js/bootstrap.min.js' %}"></script>
        <script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});</script>
        <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>
        <script type="text/javascript" src="{% static 'control/js/math.js' %}"></script>
    </body>
</html>