blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('page/<int:page_id>/', views.index, name='index'),
    path('article/<str:article_slug>/', views.article, name='article'),
    path('category/', views.category, name='category'),
    path('category/page/<int:page_id>/', views.category, name='category'),
    path('category/<str:category_slug>/', views.category_detail, name='category_detail'),
    path('category/<str:category_slug>/page/<int:page_id>/', views.category_detail, name='category_detail'),
    path('tag/', views.tag, name='tag'),
    path('tag/page/<int:page_id>/', views.tag, name='tag'),
    path('tag/<str:tag_slug>/', views.tag_detail, name='tag_detail'),
    path('tag/<str:tag_slug>/page/<int:page_id>/', views.tag_detail, name='tag_detail'),
    path('archive/', views.archive, name='archive'),
    path('archive/<int:year>/<int:month>/', views.archive_detail, name='archive_detail'),
    path('archive/<int:year>/<int:month>/page/<int:page_id>/', views.archive_detail, name='archive_detail'),
    path('link/', views.link, name='link'),
    path('link/page/<int:page_id>/', views.link, name='link'),
    path('search/', views.search, name="search"),
    path('search/page/<int:page_id>/', views.search, name="search"),
    path('<str:article_slug>.html', views.article, name='page'),
]

nitroblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('control/', include('control.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=32, unique=True)
    password = models.CharField(max_length=256)
    mail = models.CharField(max_length=200, unique=True)
    url = models.CharField(max_length=200)
    nickname = models.CharField(max_length=32, unique=True)
    create_time = models.DateTimeField()
    last_login_time = models.DateTimeField()
    group = models.CharField(max_length=32)


class Content(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, unique=True)
    create_time = models.DateTimeField()
    edit_time = models.DateTimeField()
    summary = models.TextField()
    text = models.TextField()
    priority_id = models.IntegerField()
    author_id = models.ForeignKey(User, on_delete=models.CASCADE)
    type = models.CharField(max_length=16)


class Comment(models.Model):
    content_id = models.ForeignKey(Content, on_delete=models.CASCADE)
    create_time = models.DateTimeField()
    edit_time = models.DateTimeField()
    author_id = models.ForeignKey(User, on_delete=models.CASCADE)
    author_ip = models.CharField(max_length=64)
    status = models.CharField(max_length=16)
    text = models.TextField()
    parent_id = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)


class Meta(models.Model):
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, unique=True)
    type = models.CharField(max_length=32)
    description = models.TextField()
    priority_id = models.IntegerField()


class Link(models.Model):
    name = models.CharField(max_length=200)
    url = models.CharField(max_length=200)


class Setting(models.Model):
    name = models.CharField(max_length=32)
    value = models.TextField()


class Relationship(models.Model):
    content_id = models.ForeignKey(Content, on_delete=models.CASCADE)
    meta_id = models.ForeignKey(Meta, on_delete=models.CASCADE)

blog/forms.py
from django import forms

from .models import Meta


class LoginForm(forms.Form):
    username = forms.SlugField(max_length=32, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '用户名',}))
    password = forms.CharField(max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '密码',}))


class CommentCreateForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control',}))
    id = forms.IntegerField(initial=0, widget=forms.TextInput(attrs={'style': 'display: none;'}))


class RegisterForm(forms.Form):
    username = forms.SlugField(max_length=32, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password_confirm = forms.CharField(max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    url = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    nickname = forms.CharField(max_length=32, widget=forms.TextInput(attrs={'class': 'form-control'}))

blog/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import RequestContext
from django.urls import reverse
from django.db.models import F
from django.db import connection, ProgrammingError, IntegrityError

import markdown, pypandoc, datetime

from .models import *
from .forms import *
from .common import *


def get_basic_info(request):
    basic_info = {}

    if request.session.get('is_login') is None:
        basic_info['is_login'] = False
    else:
        basic_info['is_login'] = True
        user_info = User.objects.get(id=int(request.session['user_id']))
        basic_info['user_nickname'] = user_info.nickname
        basic_info['user_email'] = user_info.mail

    basic_info['blog_name'] = Setting.objects.get(name='blog_name').value
    basic_info['page_size'] = int(Setting.objects.get(name='page_size').value)
    basic_info['meta_page_size'] = int(Setting.objects.get(name='meta_page_size').value)
    basic_info['number_of_category'] = Meta.objects.filter(type='category').count()
    basic_info['number_of_tag'] = Meta.objects.filter(type='tag').count()
    basic_info['number_of_link'] = Link.objects.all().count()
    basic_info['github'] = Setting.objects.get(name='github').value
    basic_info['weibo'] = Setting.objects.get(name='weibo').value
    return basic_info


def get_content_category_list(content_id):
    category_list_query = 'SELECT id, name, slug ' \
                          'FROM blog_meta ' \
                          'WHERE id in (' \
                          'SELECT meta_id_id ' \
                          'FROM blog_relationship ' \
                          'WHERE content_id_id = %s ' \
                          ')' \
                          'AND type = "category";' % content_id

    return Meta.objects.raw(category_list_query)


def get_content_tag_list(tag_id):
    tag_list_query = 'SELECT id, name, slug ' \
                     'FROM blog_meta ' \
                     'WHERE id in (' \
                     'SELECT meta_id_id ' \
                     'FROM blog_relationship ' \
                     'WHERE content_id_id = %s ' \
                     ')' \
                     'AND type = "tag";' % tag_id

    return Meta.objects.raw(tag_list_query)


def login(request):
    if request.session.get('is_login', None):
        return HttpResponseRedirect(reverse('blog:index', args=()))

    login_message = None

    if request.method == 'POST':
        form_info = LoginForm(request.POST)
        if form_info.is_valid():
            username = form_info.cleaned_data['username']
            password = form_info.cleaned_data['password']
            try:
                user = User.objects.get(username=username)
                if password_encrypt(password) == user.password:
                    request.session['is_login'] = True
                    request.session['username'] = user.username
                    request.session['user_group'] = user.group
                    request.session['user_id'] = user.id
                    user.last_login_time = datetime.datetime.now()
                    user.save()
                    return HttpResponseRedirect(reverse('blog:index', args=()))
                else:
                    login_message = '用户名或密码错误！'
            except User.DoesNotExist:
                login_message = '用户名或密码错误！'
        else:
            login_message = '请检查输入格式！'

    form_info = LoginForm()
    return render(request, 'blog/login.html', locals())


def logout(request):
    if not request.session.get('is_login', None):
        return HttpResponseRedirect(reverse('blog:index', args=()))

    request.session.flush()

    return HttpResponseRedirect(reverse('blog:index', args=()))


def register(request):
    if request.session.get('is_login') is not None:
        return HttpResponseRedirect(reverse('blog:index', args=()))

    basic_info = get_basic_info(request)
    response_message = ''

    if request.method == 'POST':
        form_info = RegisterForm(request.POST)
        if form_info.is_valid():
            if request.POST['password'] == request.POST['password_confirm']:
                password = password_encrypt(request.POST['password_confirm'])
                operation_query = '''
                    INSERT INTO blog_user
                    VALUES (NULL, '%s', '%s', '%s', '%s', '%s', NOW(), NOW(), 'user');
                    ''' % (request.POST['username'], password, request.POST['email'],
                           request.POST['url'], request.POST['nickname'])
                try:
                    cursor = connection.cursor()
                    cursor.execute(operation_query)
                    return HttpResponseRedirect(reverse('blog:index', args=()))
                except ProgrammingError:
                    response_message = '注册失败！'
                    return render(request, 'blog/register.html', locals())
                except IntegrityError:
                    response_message = '用户名已经存在！'
                    return render(request, 'blog/register.html', locals())
            else:
                response_message = '密码输入不一致！'
                return render(request, 'blog/register.html', locals())
        else:
            response_message = '请检查输入格式！'
            return render(request, 'blog/register.html', locals())

    form_info = RegisterForm()
    return render(request, 'blog/register.html', locals())


def index(request, page_id=1):
    basic_info = get_basic_info(request)
    basic_info['number_of_article'] = Content.objects.filter(type='article').count()
    basic_info['number_of_article_page'] = ceil(basic_info['number_of_article'], basic_info['page_size'])

    left_range = 0 + basic_info['page_size'] * (page_id - 1)

    article_list_query = 'SELECT * FROM blog_content ' \
                         'WHERE blog_content.type = "article" ' \
                         'ORDER BY blog_content.create_time DESC ' \
                         'LIMIT %s, %s;' % (left_range, basic_info['page_size'])

    article_list = Content.objects.raw(article_list_query)
    page_list = Content.objects.filter(type='page').order_by('priority_id')
    category_list = []
    tag_list = []

    for article_item in article_list:
        article_item.summary = pypandoc.convert(article_item.summary, 'html', format='md')
        raw_category_list = get_content_category_list(article_item.id)
        category_list.append(raw_category_list)
        raw_tag_list = get_content_tag_list(article_item.id)
        tag_list.append(raw_tag_list)

    context = {
        'article_list': article_list,
        'category_list': category_list,
        'page_list': page_list,
        'tag_list': tag_list,
        'basic_info': basic_info,
        'page_id': page_id,
    }

    return render(request, 'blog/index.html', context)


def article(request, article_slug):
    try:
        article_info = Content.objects.get(slug=article_slug)
    except (KeyError, Content.DoesNotExist):
        raise Http404('Could not found this page!')

    response_message = ''

    if request.method == 'POST':
        if request.session.get('is_login') is None:
            return HttpResponseRedirect(reverse('blog:login', args=()))

        if int(request.POST['id']) != 0:
            try:
                comment_info = Comment.objects.get(id=int(request.POST['id']))
            except (KeyError, Content.DoesNotExist):
                return HttpResponseRedirect(reverse('blog:article', args=article_slug))

        if request.META.get('HTTP_X_FORWARDED_FOR') is not None:
            ip = request.META['HTTP_X_FORWARDED_FOR']
        else:
            ip = request.META['REMOTE_ADDR']

        if int(request.POST['id']) == 0:
            comment_id = 'NULL'
        else:
            comment_id = int(request.POST['id'])

        comment_commit_query = '''
        INSERT INTO blog_comment
        VALUES (NULL, '%s', '%s', '%s', 'rejected', '%s', %s, %s, %s);
        ''' % (datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"), datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        ip, request.POST['text'], request.session['user_id'], article_info.id, comment_id)

        try:
            cursor = connection.cursor()
            cursor.execute(comment_commit_query)
        except ProgrammingError:
            response_message = '操作失败！'
            cursor = connection.cursor()

    basic_info = get_basic_info(request)

    page_list = Content.objects.filter(type='page').order_by('priority_id')
    category_list = get_content_category_list(article_info.id)
    tag_list = get_content_tag_list(article_info.id)

    article_info.text = pypandoc.convert(article_info.text, 'html5', format='md', extra_args=['--mathjax',
             '--smart', '--no-highlight'])

    comment_commit_form_info = CommentCreateForm()

    return render(request, 'blog/article.html', locals())


def category(request, page_id=1):
    basic_info = get_basic_info(request)
    basic_info['number_of_category'] = Meta.objects.filter(type='category').count()
    basic_info['number_of_category_page'] = ceil(basic_info['number_of_category'], basic_info['meta_page_size'])
    left_range = 0 + basic_info['meta_page_size'] * (page_id - 1)

    category_query = '''SELECT blog_meta.id, blog_meta.name, blog_meta.slug, blog_meta.description, COUNT(blog_content.id)
                        FROM blog_meta LEFT OUTER JOIN (blog_content, blog_relationship) ON (blog_meta.id = blog_relationship.meta_id_id
                        AND blog_content.id = blog_relationship.content_id_id)
                        WHERE blog_meta.type = "category"
                        GROUP BY blog_meta.id
                        ORDER BY blog_meta.priority_id
                        LIMIT %s, %s;
    ''' % (left_range, basic_info['meta_page_size'])

    cursor = connection.cursor()
    cursor.execute(category_query)
    category_list = cursor.fetchall()

blog/templates/blog/archive_detail.html
{% extends 'blog/base.html' %}
{% load blog_extras %}
{% block container %}
<div class="page-content col-lg-9">

     <div class="alert alert-primary" role="alert">
         <i class="fas fa-cube"></i> 归档：{{ year }} 年 {{ month }} 月 <span class="badge badge-pill badge-light" href="#">{{ basic_info.number_of_article }}</span>
     </div>

    {% for article in article_list %}
    <div class="card">
        <div class="card-body">
            <h1 class="card-title">{{ article.title }}</h1>
            <hr>
            <div class="card-text">{{ article.summary|safe }}</div>
            <a href="{% url 'blog:article' article.slug %}" class="page-content-button btn btn-primary">阅读全文</a>
        </div>
        <div class="card-footer">
            <span class="badge badge-warning"><i class="fas fa-calendar-day"></i> {{ article.create_time }}</span>
            <span class="badge badge-success"><i class="fas fa-user"></i> {{ article.author_id.nickname }}</span>
            {% get_element_from_index category_list forloop.counter0 as raw_category_list %}
            {% for category in raw_category_list %}
            <a class="badge badge-dark" href="{% url 'blog:category_detail' category.slug %}"><i class="fas fa-cube"></i> {{ category.name }}</a>
            {% endfor %}
            {% get_element_from_index tag_list forloop.counter0 as raw_tag_list %}
            {% for tag in raw_tag_list %}
            <a class="badge badge-primary" href="{% url 'blog:tag_detail' tag.slug %}"><i class="fas fa-tag"></i> {{ tag.name }}</a>
            {% endfor %}
        </div>
    </div>
    {% endfor %}

    <nav>
        <ul class="pagination">
            {% if page_id > 1 %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:archive_detail' year month page_id|add:-1 %}"><i class="fas fa-arrow-left"></i> 上一页</a></li>
            {% endif %}
            {% if page_id > 2 %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:archive_detail' year month page_id|add:-2 %}">{{ page_id|add:-2 }}</a></li>
            {% endif %}
            {% if page_id > 1 %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:archive_detail' year month page_id|add:-1 %}">{{ page_id|add:-1 }}</a></li>
            {% endif %}

            <li class="page-item active"><a class="page-link" href="#">{{ page_id }}</a></li>

            {% if page_id < basic_info.number_of_article_page %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:archive_detail' year month page_id|add:1 %}">{{ page_id|add:1 }}</a></li>
            {% endif %}
            {% if page_id|add:1 < basic_info.number_of_article_page %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:archive_detail' year month page_id|add:2 %}">{{ page_id|add:2 }}</a></li>
            {% endif %}
            {% if page_id < basic_info.number_of_article_page %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:archive_detail' year month page_id|add:1 %}"><i class="fas fa-arrow-right"></i> 下一页</a></li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}

blog/templates/blog/article.html
{% extends 'blog/base.html' %}
{% load comment_tree %}
{% block container %}
<div class="page-article col-lg-9">
    {% if response_message %}
    <div class="alert alert-warning" role="alert">
        <i class="fas fa-exclamation-triangle"></i> {{ response_message }}！
    </div>
    {% endif %}
    <div class="card">
        <article class="card-body">
            <h1 class="card-title">{{ article_info.title }}</h1>
            <hr>
            <div class="card-text">{{ article_info.text|safe }}</div>
        </article>
        <div class="card-footer">
            <span class="badge badge-warning"><i class="fas fa-calendar-day"></i> {{ article_info.create_time }}</span>
            <span class="badge badge-success"><i class="fas fa-user"></i> {{ article_info.author_id.nickname }}</span>
            {% for category in category_list %}
            <a class="badge badge-dark" href="{% url 'blog:category_detail' category.slug %}"><i class="fas fa-cube"></i> {{ category.name }}</a>
            {% endfor %}
            {% for tag in tag_list %}
            <a class="badge badge-primary" href="{% url 'blog:tag_detail' tag.slug %}"><i class="fas fa-tag"></i> {{ tag.name }}</a>
            {% endfor %}
        </div>
    </div>
    {% if basic_info.is_login == True %}
    <a href="#" class="page-article-comment-add page-content-button btn btn-primary comment-reply" data-toggle="modal" data-target="#commentModal" id="0">发表评论</a>
    {% else %}
    <a href="{% url 'blog:login' %}" class="page-article-comment-add page-content-button btn btn-secondary">登录后发表评论</a>
    {% endif %}
    {% autoescape off %}
    {% get_comments article_info.id %}
    {% endautoescape %}
</div>
<div class="modal fade bd-example-modal-lg" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">评论</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{% url 'blog:article' article_info.slug %}" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                    {{ comment_commit_form_info.id }}
                    {{ comment_commit_form_info.text }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                    <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
{% load blog_extras %}
{% url 'blog:category' as url_category %}
{% url 'blog:category_detail' as url_category_detail %}
{% get_view_name request.path as view_name %}
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'blog/css/code.css' %}">
        <link rel="stylesheet" href="{% static 'blog/fontawesome/css/all.css' %}">

        <title>{{ basic_info.blog_name }}</title>
    </head>

    <body>
        <div class="page-navbar">

            <nav class="navbar navbar-expand-lg navbar-light shadow-sm bg-white rounded d-flex">

                <a class="navbar-brand page-navbar-title" href="{% url 'blog:index' %}">{{ basic_info.blog_name }}</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                            <a class="nav-link" href="/">首页</a>
                        </li>
                        {% for page in page_list %}
                        {% str_cat page.slug '.html' as file_name %}
                        <li class="nav-item {% if view_name == file_name %}active{% endif %}">
                            <a class="nav-link" href="{% url 'blog:page' page.slug %}">{{ page.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

            </nav>

        </div>

        <div class="page-container container-fluid">

            <div class="row">

                <div class="page-sidebar col-lg-3">
                    {% if basic_info.is_login == True %}
                    <div class="card">
                        <img class="card-img-top" src="{% get_gravatar basic_info.user_email %}" alt="Card image cap">
                        <div class="card-body">
                            <h2 class="card-title">{{ basic_info.user_nickname }}</h2>
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'blog:logout' %}" class="page-content-button btn btn-primary login-button">退出登录</a>
                        </div>
                    </div>
                    {% else %}
                    <div class="card">
                        <div class="card-body">
                            <a href="{% url 'blog:login' %}" class="page-content-button btn btn-primary login-button">登录</a>
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'blog:register' %}" class="page-content-button btn btn-primary login-button">注册</a>
                        </div>
                    </div>
                    {% endif %}

                    <form class="input-group mb-3" method="get" action="{% url 'blog:search' %}">
                        <input type="text" class="form-control" placeholder="搜索" id="keyword" name="keyword">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="submit" id="button-addon2"><i class="fas fa-search"></i></button>
                        </div>
                    </form>

                    <div class="list-group">
                        <a href="{% url 'blog:category' %}" class="list-group-item list-group-item-action {% if view_name == 'category' %}active{% endif %}"><span class="page-sidebar-list-content"><i class="fas fa-cube"></i>分类<span class="badge badge-pill {% if view_name == 'category' %}badge-light{% else %}badge-primary{% endif %}">{{ basic_info.number_of_category }}</span></span></a>
                        <a href="{% url 'blog:tag' %}" class="list-group-item list-group-item-action {% if view_name == 'tag' %}active{% endif %}"><span class="page-sidebar-list-content"><i class="fas fa-tags"></i>标签<span class="badge badge-pill {% if view_name == 'tag' %}badge-light{% else %}badge-primary{% endif %}">{{ basic_info.number_of_tag }}</span></span></a>
                        <a href="{% url 'blog:archive' %}" class="list-group-item list-group-item-action {% if view_name == 'archive' %}active{% endif %}"><span class="page-sidebar-list-content"><i class="fas fa-archive"></i>归档</span></a>
                        <a href="{% url 'blog:link' %}" class="list-group-item list-group-item-action {% if view_name == 'link' %}active{% endif %}"><span class="page-sidebar-list-content"><i class="fas fa-link"></i>链接<span class="badge badge-pill {% if view_name == 'link' %}badge-light{% else %}badge-primary{% endif %}">{{ basic_info.number_of_link }}</span></span></a>
                    </div>


                    <div class="list-group">
                        <a href="https://github.com/{{ basic_info.github }}" class="list-group-item list-group-item-action" target="_blank"><span class="page-sidebar-list-content"><i class="fab fa-github"></i>GitHub</span></a>
                        <a href="https://weibo.com/{{ basic_info.weibo }}" class="list-group-item list-group-item-action" target="_blank"><span class="page-sidebar-list-content"><i class="fas fa-hashtag"></i>微博</span></a>
                    </div>
                </div>

                {% block container %}
                {% endblock %}

            </div>

        </div>

        <footer class="footer py-3">
            <div class="container">
                <span class="text-muted">Copyright &copy; 2019 {{ basic_info.blog_name }}.</span>
            </div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
        <script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});</script>
        <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
        <script type="text/javascript" src="{% static 'blog/js/math.js' %}"></script>
        <script type="text/javascript" src="{% static 'blog/js/control.js' %}"></script>
    </body>
</html>

blog/templates/blog/search.html
{% extends 'blog/base.html' %}
{% load blog_extras %}
{% block container %}
<div class="page-content col-lg-9">

    <div class="alert alert-primary" role="alert">
         <i class="fas fa-search"></i> 搜索：{{ keyword }} <span class="badge badge-pill badge-light" href="#">{{ basic_info.number_of_article }}</span>
    </div>

    {% if not article_list %}
    <div class="alert alert-warning" role="alert">
        <h2 class="alert-heading"><i class="fas fa-exclamation-triangle"></i> 未找到任何结果</h2>
        请修改关键词后再试。
    </div>
    {% else %}
    {% for article in article_list %}
    <div class="card">
        <div class="card-body">
            <h1 class="card-title">{{ article.title }}</h1>
            <hr>
            <div class="card-text">{{ article.summary|safe }}</div>
            <a href="{% url 'blog:article' article.slug %}" class="page-content-button btn btn-primary">阅读全文</a>
        </div>
        <div class="card-footer">
            <span class="badge badge-warning"><i class="fas fa-calendar-day"></i> {{ article.create_time }}</span>
            <span class="badge badge-success"><i class="fas fa-user"></i> {{ article.author_id.nickname }}</span>
            {% get_element_from_index category_list forloop.counter0 as raw_category_list %}
            {% for category in raw_category_list %}
            <a class="badge badge-dark" href="{% url 'blog:category_detail' category.slug %}"><i class="fas fa-cube"></i> {{ category.name }}</a>
            {% endfor %}
            {% get_element_from_index tag_list forloop.counter0 as raw_tag_list %}
            {% for tag in raw_tag_list %}
            <a class="badge badge-primary" href="{% url 'blog:tag_detail' tag.slug %}"><i class="fas fa-tag"></i> {{ tag.name }}</a>
            {% endfor %}
        </div>
    </div>
    {% endfor %}

    <nav>
        <ul class="pagination">
            {% if page_id > 1 %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:search' page_id|add:-1 %}?keyword={{ keyword }}"><i class="fas fa-arrow-left"></i> 上一页</a></li>
            {% endif %}
            {% if page_id > 2 %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:search' page_id|add:-2 %}?keyword={{ keyword }}">{{ page_id|add:-2 }}</a></li>
            {% endif %}
            {% if page_id > 1 %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:search' page_id|add:-1 %}?keyword={{ keyword }}">{{ page_id|add:-1 }}</a></li>
            {% endif %}

            <li class="page-item active"><a class="page-link" href="#">{{ page_id }}</a></li>

            {% if page_id < basic_info.number_of_article_page %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:search' page_id|add:1 %}?keyword={{ keyword }}">{{ page_id|add:1 }}</a></li>
            {% endif %}
            {% if page_id|add:1 < basic_info.number_of_article_page %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:search' page_id|add:2 %}?keyword={{ keyword }}">{{ page_id|add:2 }}</a></li>
            {% endif %}
            {% if page_id < basic_info.number_of_article_page %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:search' page_id|add:1 %}?keyword={{ keyword }}"><i class="fas fa-arrow-right"></i> 下一页</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock %}