blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('page/<int:page_id>/', views.index, name='index'),
    path('article/<str:article_slug>/', views.article, name='article'),
    path('category/', views.category, name='category'),
    path('category/page/<int:page_id>/', views.category, name='category'),
    path('category/<str:category_slug>/', views.category_detail, name='category_detail'),
    path('category/<str:category_slug>/page/<int:page_id>/', views.category_detail, name='category_detail'),
    path('tag/', views.tag, name='tag'),
    path('tag/page/<int:page_id>/', views.tag, name='tag'),
    path('tag/<str:tag_slug>/', views.tag_detail, name='tag_detail'),
    path('tag/<str:tag_slug>/page/<int:page_id>/', views.tag_detail, name='tag_detail'),
    path('archive/', views.archive, name='archive'),
    path('archive/<int:year>/<int:month>/', views.archive_detail, name='archive_detail'),
    path('archive/<int:year>/<int:month>/page/<int:page_id>/', views.archive_detail, name='archive_detail'),
    path('link/', views.link, name='link'),
    path('link/page/<int:page_id>/', views.link, name='link'),
    path('search/', views.search, name="search"),
    path('search/page/<int:page_id>/', views.search, name="search"),
    path('<str:article_slug>.html', views.article, name='page'),
]

control/urls.py
from django.urls import path

from . import views


app_name = 'control'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('forbidden/', views.forbidden, name='forbidden'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('personal-information/', views.personal_information, name='personal_information'),
    path('change-password/', views.change_password, name='change_password'),
    path('setting/', views.setting, name='setting'),
    path('manage/article/', views.article_list, name='article_list'),
    path('manage/article/page/<int:page_id>/', views.article_list, name='article_list'),
    path('manage/single-page/', views.page_list, name='page_list'),
    path('manage/single-page/page/<int:page_id>/', views.page_list, name='page_list'),
    path('manage/category/', views.category_list, name='category_list'),
    path('manage/category/page/<int:page_id>/', views.category_list, name='category_list'),
    path('manage/tag/', views.tag_list, name='tag_list'),
    path('manage/tag/page/<int:page_id>/', views.tag_list, name='tag_list'),
    path('manage/user/', views.user_list, name='user_list'),
    path('manage/user/page/<int:page_id>/', views.user_list, name='user_list'),
    path('manage/comment/', views.comment_list, name='comment_list'),
    path('manage/comment/page/<int:page_id>/', views.comment_list, name='comment_list'),
    path('manage/link/', views.link_list, name='link_list'),
    path('manage/link/page/<int:page_id>/', views.link_list, name='link_list'),
    path('create/article/', views.article_create, name='article_create'),
    path('create/page/', views.page_create, name='page_create'),
    path('create/category/', views.category_create, name='category_create'),
    path('create/tag/', views.tag_create, name='tag_create'),
    path('create/user/', views.user_create, name='user_create'),
    path('create/link/', views.link_create, name='link_create'),
    path('edit/article/<int:article_id>/', views.article_edit, name='article_edit'),
    path('edit/page/<int:page_id>/', views.page_edit, name='page_edit'),
    path('edit/category/<int:category_id>/', views.category_edit, name='category_edit'),
    path('edit/tag/<int:tag_id>/', views.tag_edit, name='tag_edit'),
    path('edit/user/<int:user_id>/', views.user_edit, name='user_edit'),
    path('edit/link/<int:link_id>/', views.link_edit, name='link_edit'),
]

nitroblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('control/', include('control.urls')),
    path('admin/', admin.site.urls),
]

control/models.py
from django.db import models

# Create your models here.

control/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import RequestContext
from django.urls import reverse
from django.db.models import F
from django.db import connection, ProgrammingError, IntegrityError
import hashlib, base64, datetime


from blog.common import *
from blog.models import *
from blog.views import get_basic_info, get_content_category_list
from .forms import *


def login(request):
    if request.session.get('is_login', None):
        return HttpResponseRedirect(reverse('control:dashboard', args=()))

    login_message = None

    if request.method == 'POST':
        form_info = LoginForm(request.POST)
        if form_info.is_valid():
            username = form_info.cleaned_data['username']
            password = form_info.cleaned_data['password']
            try:
                user = User.objects.get(username=username)
                if password_encrypt(password) == user.password:
                    request.session['is_login'] = True
                    request.session['user_id'] = user.id
                    user.last_login_time = datetime.datetime.now()
                    user.save()
                    return HttpResponseRedirect(reverse('control:dashboard', args=()))
                else:
                    login_message = '用户名或密码错误！'
            except User.DoesNotExist:
                login_message = '用户名或密码错误！'
        else:
            login_message = '请检查输入格式！'

    form_info = LoginForm()
    return render(request, 'control/login.html', locals())


def logout(request):
    if not request.session.get('is_login', None):
        return HttpResponseRedirect(reverse('control:login', args=()))

    request.session.flush()

    return HttpResponseRedirect(reverse('control:login', args=()))


def forbidden(request):
    if request.session.get('is_login') is None:
        return HttpResponseRedirect(reverse('control:login', args=()))

    return render(request, 'control/forbidden.html', locals())


def dashboard(request):
    if request.session.get('is_login') is None:
        return HttpResponseRedirect(reverse('control:login', args=()))

    number = {
        'article': Content.objects.filter(type='article').count(),
        'comment': Comment.objects.all().count(),
        'category': Meta.objects.filter(type='category').count(),
        'tag': Meta.objects.filter(type='tag').count(),
    }

    recent_article_list_query = '''
    SELECT title, slug, id
    FROM blog_content
    WHERE type = 'article'
    ORDER BY create_time DESC
    LIMIT 0, 10;
    '''

    recent_comment_list_query = '''
    SELECT blog_comment.text, blog_user.username
    FROM blog_comment, blog_user
    WHERE blog_comment.author_id_id = blog_user.id
    ORDER BY blog_comment.create_time DESC
    LIMIT 0, 10;
    '''

    cursor = connection.cursor()
    cursor.execute(recent_article_list_query)
    recent_article_list = cursor.fetchall()
    cursor.execute(recent_comment_list_query)
    recent_comment_list = cursor.fetchall()

    context = {
        'number': number,
        'recent_article_list': recent_article_list,
        'recent_comment_list': recent_comment_list,
    }

    return render(request, 'control/general/dashboard.html', context)


def personal_information(request):
    if request.session.get('is_login') is None:
        return HttpResponseRedirect(reverse('control:login', args=()))

    response_message = ''

    if request.method == 'POST':
        form_info = PersonalInformationForm(request.POST)
        if form_info.is_valid():
            operation_query = '''
            UPDATE blog_user
            SET mail = '%s',
            url = '%s',
            nickname = '%s'
            WHERE username = '%s';
            ''' % (form_info.cleaned_data['email'], form_info.cleaned_data['url'], form_info.cleaned_data['nickname'], User.objects.get(id=request.session['user_id']).username)
            try:
                cursor = connection.cursor()
                cursor.execute(operation_query)
                response_message = '更新成功！'
            except ProgrammingError:
                response_message = '更新失败！'
        else:
            response_message = '请检查输入格式！'

    user_info = User.objects.get(username=User.objects.get(id=request.session['user_id']).username)
    form_info = PersonalInformationForm()
    form_info['email'].initial = user_info.mail
    form_info['url'].initial = user_info.url
    form_info['nickname'].initial = user_info.nickname
    return render(request, 'control/general/personal_information.html', locals())


def change_password(request):
    if request.session.get('is_login') is None:
        return HttpResponseRedirect(reverse('control:login', args=()))

    response_message = ''

    if request.method == 'POST':
        form_info = PasswordChangeForm(request.POST)
        if form_info.is_valid():
            user = User.objects.get(username=User.objects.get(id=request.session['user_id']).username)
            if user.password == password_encrypt(form_info.cleaned_data['current_password']) and form_info.cleaned_data['new_password'] == form_info.cleaned_data['new_password_confirm']:
                try:
                    user.password = password_encrypt(form_info.cleaned_data['new_password'])
                    user.save()
                    response_message = '修改成功！'
                except (ProgrammingError, NameError):
                    response_message = '修改失败！'
            else:
                response_message = '密码输入错误！'
        else:
            response_message = '请检查输入格式！'

    form_info = PasswordChangeForm()
    return render(request, 'control/general/change_password.html', locals())


def article_list(request, page_id=1):
    if request.session.get('is_login') is None:
        return HttpResponseRedirect(reverse('control:login', args=()))

    if User.objects.get(id=request.session['user_id']).group != 'administrator' and User.objects.get(id=request.session['user_id']).group != 'writer':
        return HttpResponseRedirect(reverse('control:forbidden', args=()))

    response_message = ''

    if request.method == 'POST':
        article_id_list = request.POST.getlist('article_cid[]')
        article_id_set = ''
        if article_id_list:
            flag = 0
            for article_id in article_id_list:
                if flag > 0:
                    article_id_set += ', '
                article_id_set += article_id
                flag += 1
            operation_query = '''
            SELECT * FROM blog_content
            WHERE id in (%s) 
            ''' % article_id_set
            if User.objects.get(id=request.session['user_id']).group != 'administrator':
                operation_query += '''
                AND author_id_id = %s
                ''' % request.session['user_id']

            try:
                article_list = Content.objects.raw(operation_query)
                for article in article_list:
                    article.delete()
            except (NameError, ProgrammingError):
                response_message = '删除失败！'

    keyword = request.GET.get('keyword')
    category_id = request.GET.get('category')

    if keyword is None:
        keyword = ''
    if category_id is None:
        category_id = 0
    else:
        category_id = int(category_id)

    page_size = 10
    basic_info = get_basic_info(request)
    basic_info['number_of_article'] = 0

    number_of_article_query = '''
    SELECT COUNT(id)
    FROM blog_content
    WHERE type = 'article'
    '''

    if User.objects.get(id=request.session['user_id']).group == 'writer':
        number_of_article_query += '''
        AND author_id_id = %s
        ''' % request.session['user_id']

    if keyword != '':
        number_of_article_query += '''
        AND title LIKE '%%%%%s%%%%'
        ''' % keyword

    if category_id != 0:
        number_of_article_query += '''
        AND id in (
            SELECT content_id_id
            FROM blog_relationship
            WHERE meta_id_id = %s
        )
        ''' % category_id

    cursor = connection.cursor()
    cursor.execute(number_of_article_query)
    basic_info['number_of_article'] = cursor.fetchone()[0]
    basic_info['number_of_article_page'] = ceil(basic_info['number_of_article'], page_size)

    left_range = 0 + page_size * (page_id - 1)

    article_list_query = '''
    SELECT blog_content.id, blog_content.title, blog_content.edit_time, 
    COUNT(blog_comment.content_id_id), blog_content.slug, blog_content.author_id_id
    FROM blog_content LEFT OUTER JOIN blog_comment
    ON (blog_content.id = blog_comment.content_id_id)
    WHERE blog_content.type = 'article' 
    '''

    if User.objects.get(id=request.session['user_id']).group != 'administrator':
        article_list_query += '''
        AND blog_content.author_id_id = %s
        ''' % request.session['user_id']

    if keyword != '':
        article_list_query += '''
        AND blog_content.title LIKE '%%%%%s%%%%'
        ''' % keyword

    if category_id != 0:
        article_list_query += '''
        AND blog_content.id in (
            SELECT content_id_id
            FROM blog_relationship
            WHERE meta_id_id = %s
        )
        ''' % category_id

    article_list_query += '''
    GROUP BY blog_content.id
    ORDER BY blog_content.edit_time DESC
    LIMIT %s, %s;
    ''' % (left_range, page_size)

    cursor = connection.cursor()
    cursor.execute(article_list_query)
    article_list = cursor.fetchall()
    category_list_of_content = []

    for article_item in article_list:
        raw_category_list = get_content_category_list(article_item[0])
        category_list_of_content.append(raw_category_list)

    form_info = ArticleFilterForm({'keyword': keyword, 'category': category_id,})

    return render(request, 'control/manage/article_list.html', locals())


def page_list(request, page_id=1):

control/templates/control/general/change_password.html
{% extends 'control/base.html' %}
{% block container %}
                    <div class="alert alert-primary" role="alert">
                        <i class="fas fa-key"></i> 密码修改
                    </div>

                    {% if response_message %}
                    <div class="alert alert-warning" role="alert">
                        <i class="fas fa-exclamation-triangle"></i> {{ response_message }}！
                    </div>
                    {% endif %}

                    <form action="{% url 'control:change_password' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="username" class="col-sm-2 col-form-label">当前密码</label>
                            <div class="col-sm-10">
                                {{ form_info.current_password }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email" class="col-sm-2 col-form-label">新密码</label>
                            <div class="col-sm-10">
                                {{ form_info.new_password }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="url" class="col-sm-2 col-form-label">新密码确认</label>
                            <div class="col-sm-10">
                                {{ form_info.new_password_confirm }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">提交</button>
                            </div>
                        </div>
                    </form>
{% endblock %}

control/templates/control/general/dashboard.html
{% extends 'control/base.html' %}
{% load control_extras %}
{% block container %}
                    <div class="alert alert-primary" role="alert">
                        <i class="fas fa-info-circle"></i> 欢迎回来，{% get_user_username_by_id request.session.user_id %}！
                    </div>

                    <div class="cp-dashboard-info row">

                        <div class="col-lg">
                            <div class="card text-center cp-dashboard-card">
                                <div class="card-header">
                                    <i class="far fa-file-alt"></i>文章
                                </div>
                                <div class="card-body">
                                    <span class="cp-dashboard-statnumber">{{ number.article }}</span>
                                    <span class="cp-dashboard-unit">篇</span>
                                </div>
                                {% if user_group == 'administrator' or user_group == 'writer' %}
                                <div class="card-footer text-muted">
                                    <a href="{% url 'control:article_list' %}" class="btn btn-primary"><i class="fas fa-sliders-h"></i>管理</a>
                                </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg">
                            <div class="card text-center cp-dashboard-card">
                                <div class="card-header">
                                    <i class="far fa-comments"></i>评论
                                </div>
                                <div class="card-body">
                                    <span class="cp-dashboard-statnumber">{{ number.comment }}</span>
                                    <span class="cp-dashboard-unit">条</span>
                                </div>
                                {% if user_group == 'administrator' or user_group == 'writer' %}
                                <div class="card-footer text-muted">
                                    <a href="#" class="btn btn-primary"><i class="fas fa-sliders-h"></i>管理</a>
                                </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg">
                            <div class="card text-center cp-dashboard-card">
                                <div class="card-header">
                                    <i class="fas fa-cube"></i>分类
                                </div>
                                <div class="card-body">
                                    <span class="cp-dashboard-statnumber">{{ number.category }}</span>
                                    <span class="cp-dashboard-unit">个</span>
                                </div>
                                {% if user_group == 'administrator' or user_group == 'writer' %}
                                <div class="card-footer text-muted">
                                    <a href="{% url 'control:category_list' %}" class="btn btn-primary"><i class="fas fa-sliders-h"></i>管理</a>
                                </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg">
                            <div class="card text-center cp-dashboard-card">
                                <div class="card-header">
                                    <i class="fas fa-tags"></i>标签
                                </div>
                                <div class="card-body">
                                    <span class="cp-dashboard-statnumber">{{ number.tag }}</span>
                                    <span class="cp-dashboard-unit">个</span>
                                </div>
                                {% if user_group == 'administrator' or user_group == 'writer' %}
                                <div class="card-footer text-muted">
                                    <a href="{% url 'control:tag_list' %}" class="btn btn-primary"><i class="fas fa-sliders-h"></i>管理</a>
                                </div>
                                {% endif %}
                            </div>
                        </div>

                    </div>

                    {% if user_group == 'administrator' %}
                    <div class="cp-dashboard-content-list row">
                        <div class="col-lg">
                            <div class="card cp-dashboard-card">
                                <div class="card-header">
                                    <i class="far fa-file-alt"></i>最近发布的文章
                                </div>
                                <ul class="list-group list-group-flush">
                                    {% for article in recent_article_list %}
                                    <a href="{% url 'control:article_edit' article.2 %}" target="_blank" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">{{ article.0 }}</a>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>

                        <div class="col-lg">
                            <div class="card cp-dashboard-card">
                                <div class="card-header">
                                    <i class="far fa-comments"></i>最近发表的评论
                                </div>
                                <ul class="list-group list-group-flush">
                                    {% for comment in recent_comment_list %}
                                    <a href="#" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"><span class="badge badge-primary"><i class="fas fa-user"></i> {{ comment.1 }}</span>{{ comment.0 }}</a>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endif %}
{% endblock %}

control/templates/control/general/personal_information.html
{% extends 'control/base.html' %}
{% load control_extras %}
{% block container %}
                    <div class="alert alert-primary" role="alert">
                        <i class="fas fa-user-edit"></i> 个人信息修改
                    </div>

                    {% if response_message %}
                    <div class="alert alert-warning" role="alert">
                        <i class="fas fa-exclamation-triangle"></i> {{ response_message }}！
                    </div>
                    {% endif %}

                    <form action="{% url 'control:personal_information' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="username" class="col-sm-2 col-form-label">用户名</label>
                            <div class="col-sm-10">
                                <input type="text" name="username" value="{% get_user_username_by_id request.session.user_id %}" class="form-control-plaintext" readonly="" maxlength="32" required="" id="id_username">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email" class="col-sm-2 col-form-label">Email</label>
                            <div class="col-sm-10">
                                {{ form_info.email }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="url" class="col-sm-2 col-form-label">个人主页</label>
                            <div class="col-sm-10">
                                {{ form_info.url }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="nickname" class="col-sm-2 col-form-label">昵称</label>
                            <div class="col-sm-10">
                                {{ form_info.nickname }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">提交</button>
                            </div>
                        </div>
                    </form>
{% endblock %}

control/templates/control/general/setting.html
{% extends 'control/base.html' %}
{% block container %}
                    <div class="alert alert-primary" role="alert">
                        <i class="fas fa-cog"></i> 系统设置
                    </div>

                    {% if response_message %}
                    <div class="alert alert-warning" role="alert">
                        <i class="fas fa-exclamation-triangle"></i> {{ response_message }}！
                    </div>
                    {% endif %}

                    <form action="{% url 'control:setting' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="blog_name" class="col-sm-2 col-form-label">博客名</label>
                            <div class="col-sm-10">
                                {{ form_info.blog_name }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="page_size" class="col-sm-2 col-form-label">文章列表页每页显示的文章数</label>
                            <div class="col-sm-10">
                                {{ form_info.page_size }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="meta_page_size" class="col-sm-2 col-form-label">元素列表页每页显示的元素数</label>
                            <div class="col-sm-10">
                                {{ form_info.meta_page_size }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="github" class="col-sm-2 col-form-label">GitHub 账号</label>
                            <div class="col-sm-10">
                                {{ form_info.github }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="weibo" class="col-sm-2 col-form-label">微博主页</label>
                            <div class="col-sm-10">
                                {{ form_info.weibo }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">提交</button>
                            </div>
                        </div>
                    </form>
{% endblock %}